# Generated by Django 6.0 on 2026-01-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='public_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
