# Generated by Django 4.2.9 on 2026-01-08 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_public_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/images/')),
                ('hover_image', models.ImageField(blank=True, null=True, upload_to='team/hover-images/')),
                ('join_date', models.DateField(default=django.utils.timezone.now)),
                ('ending_date', models.DateField(blank=True, help_text='If set, member will not be shown after this date', null=True)),
                ('is_hidden', models.BooleanField(default=False, help_text='Hide or unhide this team member')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-join_date'],
            },
        ),
    ]
