# Generated by Django 6.0 on 2026-01-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
