# Generated by Django 6.0 on 2026-01-09 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_teammember_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamAppCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend')], max_length=20)),
                ('tech_name', models.CharField(max_length=40)),
                ('status', models.BooleanField(default=False, help_text='If true, users can select this tech')),
            ],
        ),
        migrations.CreateModel(
            name='TeamApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('using_popdrop_since', models.PositiveIntegerField(help_text='Months using PopDrop')),
                ('experience_years', models.PositiveIntegerField()),
                ('resume', models.FileField(blank=True, null=True, upload_to='team/resumes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tech_stack', models.ManyToManyField(related_name='applications', to='api.teamappcategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
