# Generated by Django 6.0 on 2026-01-09 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_teamappcategory_teamapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamapplication',
            name='experience_years',
        ),
    ]
